name: Nooro_Tracker

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    env_file:
      - .env
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - nooro_mysql_tracker_data:/var/lib/mysql
    restart: always

volumes:
  nooro_mysql_tracker_data:
